-- phpMyAdmin SQL Dump
-- version 4.3.8
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 24, 2015 at 01:06 PM
-- Server version: 5.5.40-36.1
-- PHP Version: 5.4.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `metalx_shopping`
--

-- --------------------------------------------------------

--
-- Table structure for table `cookbook`
--

CREATE TABLE IF NOT EXISTS `cookbook` (
  `id` int(11) NOT NULL,
  `pid` text NOT NULL,
  `title` text NOT NULL,
  `prep_time` text NOT NULL,
  `cook_time` text NOT NULL,
  `total_time` text NOT NULL,
  `yield` text NOT NULL,
  `description` text NOT NULL,
  `ingredients` text NOT NULL,
  `instructions` text NOT NULL,
  `comments` text NOT NULL,
  `category` text NOT NULL,
  `source` text NOT NULL,
  `tags` text NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `cookbook`
--

INSERT INTO `cookbook` (`id`, `pid`, `title`, `prep_time`, `cook_time`, `total_time`, `yield`, `description`, `ingredients`, `instructions`, `comments`, `category`, `source`, `tags`) VALUES
(4, 'iZepe5Uj', 'Beef Stroganoff', '', '', '', '', '          ', '1/2 cup onion\r\n2 T olive oil\r\ncooking spray\r\n1/2-3/4 pound round steak\r\n8 oz sliced fresh mushrooms\r\n2 garlic cloves\r\n1 tablespoon ketchup\r\npepper\r\n1/2 cup red wine\r\n1/2 cup (1/2 small container) sour cream\r\n8 oz egg noodles\r\n1 can cream of mushroom soup\r\nparsley', 'Chop 1/2 cup of onion and mince 2 garlic cloves and put aside for later.\r\nTrim all fat off meat and slice into thin strips like the size of your pinky.\r\nSpray frying pan with cooking spray and heat to medium heat.\r\nAdd olive oil to light coat the pan (approximately 2 T of oil). \r\nAdd round steak and cook until browned, turning occasionally.\r\nAdd chopped onion and minced garlic to meat.\r\nAdd sliced mushrooms to meat.\r\nCook until onions are tender and clear.     \r\nTurn heat down to medium and add can of mushroom soup, ketchup and red wine (or substitute water for red wine).\r\nStir mixture until well blended, cover, and let simmer.\r\nIf mixture begins to boil, turn heat to low.\r\nStart cooking egg noodles, once cooked add back to the same pan they were cooked in.\r\nAdd sour cream to the meat mixture and sprinkle parsley over the top of the meat mixture.\r\nStir the meat mixture until well blended.\r\nPour meat mixture over the noodles and mix together until all of the noodles are evenly covered.', 'Uses large frying pan with lid', 'dinner', 'Mom', 'Beef pasta'),
(6, 'LrIUSOuw', 'Chocolatey Dessert', '', '40 min', '', '8-10 servings', '', '1.25 cups sugar, divided\r\n1 cup all-purpose flour\r\n7 Tbs Hershey''s cocoa, divided\r\n2 tsp baking powder\r\n1/4 tsp salt\r\n1/2 cup milk\r\n1/3 cup butter or margarine, melted\r\n1.5 tsp vanilla extract\r\n1/2 cup packed light brown sugar\r\n1.25 cups hot water', 'Heat oven to 350*\r\nIn medium mixing bowl combine 3/4 cup sugar, flour, 3 tablespoons cocoa, baking powder and salt. \r\nBlend in milk, melted butter and vanilla; beat until smooth. \r\nPour batter into square pan, 8x8x2 or 9x9x2 inches. \r\nIn small bowl combine remaining 1/2 cup sugar, brown sugar and remaining 4 tablespoons cocoa; sprinkle mixture evenly over batter. \r\nPour hot water over top; do not stir. \r\nBake 40 minutes or until center is almost set. \r\nLet stand 15 minutes; spoon into dessert dishes, spooning sauce from bottom of the pan over top.', '          ', 'dessert', 'Mom', 'Chocolate'),
(15, 'qnl5js9c', 'Pot Roast', '', '', '', '', '', 'One pot roast (any cut)\r\nCarrots\r\nRed Potatoes\r\nOnion\r\nMushrooms\r\n1 can cream of mushroom soup\r\n1 can golden mushroom soup\r\n1 packet dry Lipton onion soup mix\r\nBurgundy cooking wine (1 soup can full)\r\nSalt\r\nPepper\r\nGarlic Powder', 'Add meat and vegetables to crock pot\r\nSeason with salt, pepper, and garlic powder\r\nMix together rest of ingredients and pour over roast\r\nCook 3-4 hours on high or 6-8 hours on low. When its falling apart, its done!', '', 'dinner', 'Kristen Potter', 'Crock Pot'),
(16, 'idQ7uwZf', 'Spanish Rice Yellow Rice', '', '', '', '3-4 servings', '', '1 pound round steak\r\n10 oz package yellow rice\r\n4T olive oil\r\n1/2 cup onion\r\n2 cloves garlic\r\n1 cup sliced mushrooms\r\npepper\r\n1 cube beef bouillon\r\n10 oz frozen flowerets or cuts\r\n2 T corn starch\r\n', 'Chop 1/2 cup of onion and mince 2 cloves of garlic and put aside for later\r\nTrim fat off meat and slice into thin strips like the size of your pinky\r\nPut into a large frying pan with enough olive oil to lightly coat pan\r\nBrown meat, turning occasionally\r\nAdd onion and garlic to meat\r\nAdd mushrooms to meat\r\nCook until onions are clear and tender\r\nAdd 1.5 cups water, beef bouillon and dash of pepper to meat and stir well\r\nTurn heat up to high and bring mixture to a boil, turn heat to low and cover with lid\r\nStart yellow rice following package instructions (Cooks about 25 minutes)\r\nWhen there are 8 minutes left to cook the rice add broccoli to meat mixture.\r\nTurn heat back up on meat and get to boil then lower heat and cover\r\nMix 2T cornstarch with 4 T water in small bowl to a smooth paste and set aside\r\nCook meat another 4 minutes and check if broccoli is fork tender\r\nOnce broccoli is fork tender turn heat to medium and pour 1/2 cornstarch mixture slowly around perimeter of pan\r\nStir constantly checking consistency, add cornstarch 1 tsp at a time until desired thickness (like gravy)\r\nTurn heat back down to low and cover for 1 minute before serving\r\nServe over yellow rice', 'Requires 12&quot; frying pan with lid', 'dinner', 'Mom', ''),
(17, 'FxuBMyp1', 'Chicken and Dumplings', '', '4-6 hours', '', '', '', '2 boneless, skinless chicken breasts, halved\r\n1 Tbs butter\r\n1 can low sodium cream of mushroom soup\r\n1 can low sodium cream of chicken soup\r\n1 small onion, finely diced\r\n1 10 oz container of biscuit dough, cut up\r\n2 cans mixed vegetables, drained\r\n3/4 cup low sodium chicken broth\r\nParsley\r\nPepper', 'Combine all ingredients except biscuit dough in crock pot\r\nCook on high approximately 4 hours or low approximately 6 hours. \r\n60-90 minutes before its ready, add biscuit dough', '$12-$15', 'dinner', 'All Recipes http://allrecipes.com/Recipe/Slow-Cooker-Chicken-and-Dumplings/Detail.aspx?evt19=1&amp;amp;amp;amp;amp;amp;referringHubId=1203&amp;amp;amp;amp;amp;amp;scale=4&amp;amp;amp;amp;amp;amp;ismetric=0', 'Ember, Crock Pot'),
(20, 'PrlsfRan', 'Sesame-Barbecue Steaks', '', '', '45 minutes', '4-6 servings', '', '2 lb beef flank steak\r\n2 cloves of garlic\r\n2-inch piece fresh ginger root\r\n1/4 cup sugar\r\n1/2 cup reduced sodium soy sauce\r\n1/3 cup sesame oil\r\n3 tablespoons sesame seeds\r\n1/2 tsp crushed red pepper flakes\r\nlarge ziplock bag\r\n', 'Chop garlic.\r\nPeel ginger using edge of a spoon to scrape off the skin; grate ginger very finely, then measure\r\nPlace all ingredients (except steak) in ziplock bag; seal bag and squeeze to blend mixture. Add steak to bag; seal bag tightly and let stand at least 10 minutes (up to overnight) to marinate. \r\nPreheat grill pan (or grill) on medium high 2-3 minutes. Place steak in grill pan (or on grill), reserving marinade, grill 5-6 minutes on each side, turning often, or until steak is 145* (for medium rare).\r\nPlace reserved marinade in small saucepan and bring to a full boil. Reduce heat about one-half. Remove steaks from grill let stand 5 minutes before slicing. Slice meat diagonally against the grin; drizzle with sauce. ', '', 'dinner', 'Publix Aprons', 'grill'),
(21, 'DdjTKtlA', 'Macaroni and Cheese', '', '', '', '', '', '1/2 package of elbow noodles (8 oz)\r\n1/4 cup margarine or butter\r\n3 tbsp flour\r\n1/8 tsp dry mustard\r\n1/8 tsp black pepper\r\n2 cups milk\r\n2 cups/8 oz sharp cheddar cheese (2 packs shredded)\r\n1/2 cup breadcrumbs\r\n2 tbsp melted butter (measure then melt)\r\n', 'Preheat oven to 350*\r\nCook and drain noodles. Cover to keep hot and set aside.\r\nMeanwhile, in medium saucepan, melt 3 tbsp butter on high; blend in flour, mustard, and pepper with wooden spoon.\r\nCook until mixture is smooth and bubbly then add milk and turn down a little lower. Stir constantly so that everything combines.\r\nCook and stir over medium heat until it boils, simmer 1 minute stirring constantly.\r\nAdd cheese, stir it until cheese is melted and combined\r\nAdd noodles and cheese to serving pan and mix well.\r\nMelt the rest of the butter (1 tbsp), mix with 1/2 cup breadcrumbs.\r\nLightly cover pasta and cheese with breadcrumbs.\r\nCook for 25 minutes, until breadcrumbs are golden brown. \r\n', '', 'other', 'Mom', 'potluck'),
(22, 'pvPfM0FR', 'Salmon with Lemon and Dill', '15 minutes', '25 minutes', '40 minutes', '4 servings', '', '1 pound salmon fillets\r\n1/4 cup butter, melted\r\n5 tablespoons lemon juice\r\n1 tablespoon dried dill weed\r\n1/4 teaspoon garlic powder\r\n1 fresh lemon\r\nsea salt to taste\r\nfreshly ground black pepper to taste', 'Preheat oven to 350*. \r\nLightly grease a medium baking dish.\r\nPlace salmon in the baking dish. Mix the butter, lemon juice, and dill in a small bowl, and drizzle over the salmon. Season with garlic powder, sea salt, and pepper.\r\nBake 25 minutes in the preheated oven, or until salmon is easily flaked with a fork.\r\nAdd thinly sliced lemons to the top for the final 5 minutes cooking time.', '', 'dinner', 'All Recipes tinyurl.com/kxwhvku', 'Ember, fish, healthy'),
(23, 'ESW8nzGr', 'Chicken Noodle Soup', '', '', '', '6 servings', '', '8 cups water or 8 cups canned low sodium chicken broth\r\n1 cup carrot, cut into 1/4-inch slices\r\n1 cup celery, cut into 1/4-inch slices\r\n1 cup onion, chopped\r\n1 garlic clove, minced\r\n2 bay leaves\r\n1/2 teaspoon dried thyme\r\n4 teaspoons salt (to taste)\r\n1/2 teaspoon fresh ground black pepper, to taste\r\n1 (3 1/2 lb) roasting chickens\r\n3 cups wide egg noodles, uncooked', 'In 4-1/2 to 6-quart slow-cooker bowl, combine water, carrots, celery, onion, garlic, bay leaves, thyme, 4 t salt, 1/2 t pepper.\r\nPlace whole chicken on top of vegetables.\r\nCover slow cooker with lid and cook as manufacturer directs on low setting 7-8 hours or on high 4 hours.\r\nTransfer chicken to cutting board. Discard bay leaves. Add noodles to slow-cooker; cover with lid and cook (on low or high) 20 minutes.\r\nWhile noodles cook, remove and discard skin, fat and bones from chicken; shred meat.\r\nSkim fat from soup and discard. Return chicken to soup to serve.', '', 'soup', '', 'crock pot'),
(24, 'bI6nr5ri', 'Chicken Lettuce Wraps', '', '', '35 minutes', '4 servings', 'Copycat recipe from PF Chang', '1 tablespoon olive oil\r\n1 pound ground chicken\r\n2 cloves garlic, minced\r\n1 onion, diced\r\n1/4 cup hoisin sauce\r\n2 tablespoons soy sauce\r\n1 tablespoon rice wine vinegar\r\n1 tablespoons freshly grated ginger\r\n1 teaspoon Sriracha, or more, to taste\r\n1 (8-ounce) can whole water chestnuts, drained and diced\r\n2 green onions, thinly sliced\r\nKosher salt and freshly ground black pepper, to taste\r\n1 head butter lettuce', 'Heat olive oil in a saucepan over medium high heat. Add ground chicken and cook until browned, about 3-5 minutes, making sure to crumble the chicken as it cooks; drain excess fat.\r\nStir in garlic, onion, hoisin sauce, soy sauce, rice wine vinegar, ginger and Sriracha until onions have become translucent, about 1-2 minutes. Stir in chestnuts and green onions until tender, about 1-2 minutes; season with salt and pepper, to taste.\r\nTo serve, spoon several tablespoons of the chicken mixture into the center of a lettuce leaf, taco-style.', '', 'lunch', 'http://tinyurl.com/mfqqzkn', 'dinner, potluck  '),
(25, 'uRyQi8TH', 'Strawberry Crepes', '', '', '', '', '', 'Crepes:\r\n4 eggs\r\n1/2 cup butter melted\r\n1/3 cup sugar\r\n1 cup milk\r\n1/4 cup water\r\n1 tsp. vanilla\r\n1 cup flour\r\ndash salt\r\n\r\nCream filling: 1 c sour cream, 1 8oz pkg. cream cheese, SOFTENED TO ROOM TEMPERATURE and 1 c powdered sugar ', 'In a blender, place all crepe ingredients, except flour. Blend together\r\nSprinkle in flour, blend until incorporated. \r\nYou may choose to refrigerate the batter for 1 hour or even over-night. But sometimes when I''m desperate, I just go straight to the skillet. Refrigerating the batter makes a difference though. It makes the crepes lighter and not so dense. I just stick my whole blender container in the fridge.\r\nAfter refrigerating the batter, blend again on HIGH for 1 minute. This adds air into the batter and again makes the crepe lighter and gives you that beautiful spider''s web design on your crepes.\r\nLightly butter an 8-inch non-stick skillet and place on medium heat (you may need to adjust heat according to how fast crepes are cooking, don''t cook them on high, they will burn). Pour 1/4 cup of batter into the skillet and SWIRL pan around until bottom of pan is covered with a very THIN layer of batter.\r\nCook for about 30 seconds or until edges can be lifted with a spatula\r\nUse fingers to FLIP crepe. Cook opposite side for 5-10 seconds. Crepe should slide right out of pan. Use wax paper between crepes.\r\nUse electric beater to combine ingredients to make cream filling', '', 'breakfast', 'Sally Carpenter http://tinyurl.com/mkboybh', 'Fancy'),
(26, 'DejQPM61', 'Sweet Potato Fries', '', '20 minutes', '', '', '', 'Sweet potatoes\r\nOlive oil\r\nSea Salt\r\nPepper\r\nParmesan cheese', 'Preheat oven to 400*. Pour a little olive oil on a cookie sheet. Peel and thickly slice the sweet potatoes then put them into a bowl. Pour some more olive oil over them, as well as salt, pepper, and Parmesan cheese, and toss to evenly coat them. Transfer to the oiled cookie sheet. Cook on 400 degrees for about 20 minutes.  Try one before you decide they''re done because they wont be as good if they''re too hard.', '', 'other', 'Julia', 'Vegetable, Side'),
(27, 'ST8ttWtY', 'Chicken Broccoli Bake', '15 minutes', '60 minutes', '1 hour 15 minutes', '6 servings', '', '2 Tbs butter\r\n2 Tbs vegetable oil\r\n6 small chicken breast halves\r\n1/2 tsp garlic salt\r\n1 can cream of mushroom soup\r\n1 4 oz can mushroom stems and pieces\r\n1/4 cup water\r\n1 tsp Worcestershire sauce\r\n1/2 tsp dried thyme leaves\r\n2 packages (10 oz each) frozen broccoli spears\r\n1/2 tsp sea salt\r\npaprika ', 'Preheat oven to 400*. Heat butter and oil in baking dish in oven until melted. Place chicken in dish, turning to coat in butter mixture. Arrange chicken skin sides up; sprinkle with garlic salt. Cook uncovered 30 minutes. \r\nMix soup, mushrooms (with liquid), water, Worcestershire sauce, and thyme. \r\nRinse broccoli under running cold water to separate; drain.\r\nRemove chicken from oven; drain fat from dish.\r\nArrange broccoli along sides of chicken. Sprinkle over salt. Spoon soup mixture over broccoli. \r\nCook uncovered until chicken is done and broccoli is tender, about 30 minutes. \r\nSprinkle with paprika. \r\n ', 'Try adding 2 cans of cream of mushroom soup. Ember didn''t like the broccoli on March 16th, 2015. ', 'dinner', 'Mom', 'Ember'),
(28, '3kGDKS7a', 'Cheese Stuffed Shells', '15-20 minutes', '25 minutes', '45 minutes', '6 servings', '', '12 oz Jumbo Shell pasta\r\n2 eggs\r\n2 15 oz containers ricotta cheese\r\n2 cups shredded Mozzarella cheese\r\n1.5 cups grated parmesan cheese, divided\r\n1/2 cup chopped fresh parsley or 2 tbsp dried parsley\r\n1 tbsp dried basil\r\n1 tsp sea salt\r\n3 cups spaghetti sauce', 'Preheat oven to 350*.\r\nCook Jumbo shells for 15 minutes. Drain, cover, set aside.\r\nMeanwhile, in medium bowl beat eggs lightly; stir in Ricotta, Mozzarella, 3/4 cup Parmesan, parsley, basil, and salt.\r\nSpoon about 1 tablespoon of cheese mixture into each shell.\r\nSpread spaghetti sauce on bottom of 13x9 inch pan.\r\nArrange filled shells in pan and top with spaghetti sauce.\r\nSprinkle with remaining Parmesan cheese.\r\nCover with tin foil. \r\nBake for 25-30 minutes or until heated through.\r\n', '', 'dinner', 'Back of Mueller''s pasta box', 'pasta, potluck'),
(29, 'JBer08Cf', 'Fresh Herb Penne with Chicken and Tomatoes', '20 minutes', '20 minutes', '40 minutes', '4 servings', '*Updated on March 22, 2015 with improvements. Originally used 16 oz pasta, 10-12 oz chicken, no &quot;optional&quot; additions', '12 oz Penne Rigate pasta\r\n4 tbsp extra virgin olive oil\r\n1 tsp fresh chopped garlic\r\n1 can (14.5 oz) diced tomatoes\r\n1/3 cup fresh basil leaves, chopped or cut into thin strips (may substitute 1.5 tsp dry basil)\r\n8-10 oz cooked chicken breast strips\r\n1.5 cups (6 oz) shredded Mozzarella cheese\r\nsalt and cracked black pepper to taste\r\n', 'if chicken is raw, cut into bite sized pieces and boil until cooked.\r\nMeanwhile, cook and drain pasta. \r\nMeanwhile, heat olive oil in large skillet over medium high heat.\r\nAdd garlic and cook for 1 minute\r\nAdd tomatoes, basil, and optional onion, squash, zucchini, bell pepper, eggplant, mushroom. Cook for 2+ minutes.\r\nAdd chicken; simmer for 5 minutes\r\nToss with pasta and slowly add Mozzarella cheese.\r\nSeason to taste with salt and cracked black pepper\r\nServe immediately. ', '', 'dinner', 'Back of Mueller''s Penne box', 'Pasta, Ember'),
(30, 'aLOEW5cN', 'Chili', '30 minutes', '20+ minutes', '50+ minutes', '6-7 servings', '', '1 pound ground chuck lean hamburger\r\n1 cup chopped onion\r\n2 cloves minced garlic\r\n2 16 oz cans tomatoes (diced or stewed)\r\n2 16 oz cans dark red kidney beans, drained\r\n1 16 oz can tomato sauce\r\n4 tsp chili powder\r\n1/2 tsp dried basil, crushed (optional)\r\n1/4 tsp pepper', 'Cook meat, drain grease.\r\nAdd onion and garlic. Saute.\r\nStir in undrained tomatoes, kidney beans, tomato sauce, chili powder, basil, and pepper. \r\nBring to a boil. Reduce heat, cover.\r\nSimmer 20+ minutes. ', '', 'dinner', 'Mom', ''),
(31, 'uKyGpk49', 'Creamy Ranch Chicken', '', '', '4.5-7.5 hours', '', '', 'Cooking spray\r\n1/4 tsp paprika\r\n6 boneless skinless chicken breasts\r\n1 packet of powdered ranch seasoning\r\n1/2 cup low sodium chicken broth\r\nsea salt \r\npepper\r\n1/3 cup half and half\r\n1 tsp cornstarch\r\n3 oz reduced fat cream cheese\r\n1/2 tsp parsley\r\n1/2 tsp oregano (optional)', 'Spray slow cooker with cooking spray.\r\nPlace chicken in the bottom of the slow cooker and sprinkle evenly with salt, pepper, and 1/4 tsp paprika.\r\nDump one packet of ranch dip mix over chicken, and the pour in 1/2 cup chicken broth.\r\nTurn on slow cooker and cook on high for 4 hours or low for 6-7 hours. \r\n30 minutes before serving, mix 1/3 cup half and half with 1 tsp cornstarch. Pour into slow cooker and stir to mix. Sprinkle on 1/2 tsp oregano and 1 tsp parsley.\r\nCube 3 oz of cream cheese and distribute evenly in the slow cooker liquid. Replace lid and cook for an additional 20-25 minutes. \r\nStart cooking pasta.\r\nRemove chicken to platter, stir sauce and pour over chicken. \r\nServe over pasta garnished with fresh parsley.\r\n', 'For low carb, serve with a fresh green salad, or steamed vegetables. ', 'dinner', 'Mandy', 'crock pot'),
(32, 'yrvXWpYN', 'Cream of Broccoli soup', '', '', '', '', '', '1 package broccoli, chopped or flowerets\r\n3 Tbs butter\r\n1 medium onion, chopped\r\n3-4 cubes or 4 tsp granulated chicken bouillon\r\n3-4 cups milk\r\n1/2 cup cornstarch\r\nsea salt\r\npepper\r\nShredded cheddar cheese\r\nBacon bits\r\n\r\n(Use 3 cups milk for 3 bouillons or 4 cups milk for 4 bouillons) \r\n', 'Cook broccoli according to package directions, drain.\r\nMeanwhile, chop onion and set aside.\r\nMelt butter, saute onion until clear.\r\nAdd milk, broccoli, and chicken bouillon.\r\nCook over medium heat and stir well.\r\nMix cornstarch with 1/2 cup milk, until smooth and keep nearby.\r\nIncrease soup to boiling and slowly add cornstarch mixture, stirring constantly.\r\nAs soup thickens, turn down stove to low.\r\nSeason with salt and pepper to taste.\r\nGarnish with cheddar cheese and/or bacon.', '', 'soup', 'Mom', ''),
(33, 'xWqvfEV9', 'Parmesan Carrots', '15 minutes', '20 minutes', '35 minutes', '', '', 'Carrots\r\nParmesan cheese\r\nOlive oil\r\n', 'Preheat oven to 400*.\r\nPeel and slice carrots into very thin slices.\r\nCoat with olive oil and Parmesan cheese.\r\nCook in cookie sheet for 20 minutes or until desired tenderness.', '', 'other', '', 'Vegetable'),
(34, 'OoBjGqHT', 'Cheesy Ham and Hash Brown Casserole', '', '', '', '', '', '1 32oz package frozen has brown potatoes\r\n8 oz cooked, diced ham\r\n2 10.75oz cans of condensed cream of potato soup\r\n1 16oz container sour cream\r\n2 cups shredded sharp Cheddar cheese\r\n1.5 cups grated Parmesan cheese', 'Preheat oven to 375*\r\nLightly grease a 9x13 inch baking dish\r\nIn large bowl, mix hash browns, ham, cream of potato soup, sour cream, and Cheddar cheese.  Spread evenly into prepared dish. Sprinkle with Parmesan cheese.\r\nBake 1 hour in preheated oven or until bubbly and lightly brown. Serve immediately. If serving the next day, refrigerate until ready to cook and eat. ', '', 'breakfast', 'Online site', 'Potluck'),
(35, '5XSjzNyP', 'Lasagna Al Forno', '', '35 minutes', '', '8-10 servings', '', '16 pieces (about 1 pound) Lasagna\r\n1 pound ground beef\r\n3 cups (about 26 oz jar) spaghetti sauce\r\n4 cups (32 oz) ricotta cheese\r\n2 cups (8 oz) shredded mozzarella cheese\r\n3 tablespoons grated Parmesan cheese\r\n', 'Preheat oven to 375.\r\nCook pasta according to package directions.\r\nMeanwhile, in medium saucepan, cook meat until brown; drain\r\nStir in spaghetti sauce; simmer 5 minutes.\r\nIn 13x9-inch baking dish, spread 1/2 cup meat sauce. Place 4 pasta pieces lengthwise over sauce, overlapping edges.\r\nSpread 1/3 ricotta and mozzarella cheeses over pasta; cover with 1/4 sauce.\r\nRepeat layers twice, beginning and ending with pasta.\r\nspread remaining sauce on top; sprinkle Parmesan cheese.\r\nCover with foil; bake 30 minutes or until hot and bubbly.\r\nRemove foil; bake 5 additional minutes.\r\nLet stand 5 minutes before serving.\r\n', '', 'dinner', 'pasta box', 'pasta, potluck'),
(36, 'dJrhA8w1', 'Quiche', '', '', '', '', '', '1 container diced mushrooms\r\n2 medium onions, diced\r\n1 tsp diced garlic\r\n1 package frozen spinach\r\n4 eggs\r\n1/3 cup (heaping) sour cream\r\n1/4 cup parmesan cheese\r\n8 oz shredded mozzarella cheese\r\nbacon bits (optional)\r\nPie crust', 'Preheat oven to 350*.\r\nBegin defrosting frozen spinach in a strainer, wrapped in paper towels, under slowly running water\r\nSpray large frying pan with cooking spray and saute the onions, mushrooms, and garlic until onions are clear.\r\nIn large bowl, mix eggs, sour cream, Parmesan cheese, and mozzarella cheese\r\nOnce onions are clear, drain spinach and add to the onion mixture and mix well.\r\nAdd spinach/mushroom mixture to the cheese mixture and mix well.\r\nAdd bacon bits now if you want to.\r\nPut pie crust in pie pan and pour in batter.\r\nSprinkle Parmesan cheese on top (and bacon bits if desired)\r\nBake for approximately 50 minutes.', '', 'breakfast', 'Vickie', 'Potluck'),
(37, 'R6fQXaH4', 'Balsamic Green Beans ', '', '20 minutes?', '', '', '', '1 bag of fresh green beans\r\nolive oil\r\nsea salt\r\nbalsamic vinegar\r\n', 'Snap ends off of green beans\r\nLightly coat in sea salt, olive oil, and balsamic vinegar\r\nCook on cookie sheet for 20 minutes???', '', 'other', '', 'vegetables'),
(38, '6dwSSBw9', 'Morgan''s Mexican Mix', '', '40 minutes to 4 hours', '1.25 hours- 4.5 hours', '', '', '1 can of black beans, drained\r\n2 small chicken breasts\r\n1 can of corn, drained\r\n1 cup mild salsa\r\n1/2 pound cream cheese\r\ntortillas or 1 cup dry white rice', 'Cut fat off chicken breasts.\r\nAdd all ingredients except tortillas/rice to crock pot.\r\nCook on high 4 hours.\r\nShred chicken and return to crock pot.\r\nServe over white rice or in tortillas.\r\n(For faster prep time, boil chicken breasts for 15 minutes or until fully cooked. Shred, add all ingredients and cook on high for 40 minutes.)', '', 'dinner', 'Morgan', 'Crock Pot'),
(39, 'JcyfIFi9', 'Chicken Pot Pie', '70 minutes', '30 minutes', '1 hour 50 minutes', '', '', '1 pound skinless, boneless chicken breasts, cut into small pieces\r\n1 cup sliced carrots\r\n1 cup frozen green peas\r\n1/2 cup sliced celery\r\n1/3 cup butter \r\n1/3 cup chopped onion\r\n1/3 cup all-purpose flour\r\n1/2 tsp salt\r\n1/4 tsp black pepper\r\n1 diced potato\r\n1/4 tsp celery seed\r\n1.75 cups low sodium chicken broth\r\n2/3 cup milk\r\n2 Pie crusts', 'Preheat oven to 425*\r\n1. In a saucepan, combine chicken, carrots, peas, and celery. Cover with water, boil for 15 minutes. Drain, set aside.\r\n2. In the saucepan over medium heat, cook onions in butter until soft and translucent. Stir in flour, salt, pepper, and celery seed. Slowly stir in chicken broth and milk. Simmer over medium low heat until thick. Remove from heat and set aside.\r\n3. Place chicken mixture in bottom of the pie crust. Pour hot liquid mixture over. Cover with top crust, seal edges and make slits for steam to escape. Add tin foil.\r\n4. Bake 30-35 minutes. Cool 10 minutes before serving. ', '', 'dinner', 'All Recipes http://tinyurl.com/knfzyk9', 'Ember'),
(40, 'qBru3RLf', 'Eggplant Parmesan', '1 hour', '15-20 minutes', '1 hour 20 minutes', '6 servings', '', '1 eggplant\r\nUp to 4 scrambled eggs\r\nBreadcrumbs\r\nVegetable oil\r\nMozarella cheese\r\nPasta', 'Preheat oven to 350*\r\nCut eggplant into thin slices\r\nPut raw scrambled eggs in one bowl and breadcrumbs in another. Cover each slice of eggplant in egg then in breadcrumbs. Stack on plate.\r\nHeat vegetable oil over medium to medium high heat. Fry eggplants, turning with plastic fork. Cook bigger pieces first.\r\nStack eggplants in glass dish, adding sauce and cheese between layers and on top. \r\nCook 15-20 minutes\r\nStart pasta when eggplant goes into oven.', '', 'dinner', 'Kris', 'Ember'),
(41, 'DMBOQjPf', 'Three Pepper Pasta', '', '', '', '', '', '3 cups bowtie pasta\r\n1 tbs olive oil\r\n1 small green bell pepper, cut into 1/4 inch strips\r\n1 cup tomato pasta sauce\r\nchopped fresh basil\r\nshredded Parmesan cheese', 'Cook and drain pasta.\r\nMeanwhile, in a 10 inch nonstick skillet, heat oil over medium heat. Cook bell peppers in oil about 5 minutes, stirring occasionally, until crisp-tender.\r\nStir in pasta sauce. Cook 2-3 minutes or until hot. Serve sauce over pasta. Top with basil and cheese. ', '', 'dinner', 'http://tinyurl.com/qecobzd', ''),
(42, 'hIoqnyw3', 'Tacos', '', '', '', '', '', '1 pound ground beef or boneless chicken breasts\r\n1 package Taco shells\r\n1 package taco seasoning mix \r\nTaco sauce\r\n3/4 cup water\r\nToppings:\r\nTomatoes\r\nOnions\r\nShredded cheddar cheese\r\nSour cream\r\nLettuce', 'Preheat oven to 350*\r\nBrown ground beef or chicken breasts; drain.\r\nAdd 3/4 cup water and taco seasoning mix. Heat until thickened, stirring often.\r\nBake shells for 3-4 minutes or microwave on high 20-30 seconds.\r\nFill taco shells with meat or chicken mixture and top with taco sauce and other toppings. ', '', 'dinner', '', 'Ember'),
(43, 'LYszgAcL', 'Lemon Poppy Seed Bread', '', '30-40 minutes', '', '4 mini loaves', '', 'Bread Ingredients:\r\n2.25 cup all-purpose flour\r\n1.25 cup sugar\r\n.75 cup milk\r\n1 cup softened butter\r\n3 eggs\r\n2 tbsp poppy seed\r\n1.5 baking powder\r\n1 tsp salt\r\n1 tbsp grated lemon peel\r\n\r\nGlaze Ingredients:\r\n1/3 cup sugar\r\n3 tbsp butter, melted\r\n1.5 tbsp lemon juice\r\n', 'Preheat oven to 350*\r\nGrease bottom only of 4 (5.5 x 3&quot;) mini loaf pans. In large mixer bowl combine all bread ingredients. Beat at medium speed, scraping bowl often, until well mixed (2-3 minutes).  Pour into prepared pans. Bake for 30-40 minutes or until wooden pick inserted in center comes out clean. In small bowl stir together all glaze ingredients. Pour over warm bread. Cool 10 minutes. Loosen edge with knife, remove from pan.', '', 'breakfast', 'Mom', 'Potluck, Fancy'),
(44, '7ILLAWRt', 'Quinoa Salad', '', '', '', '', '', '2 cups water\r\n\r\n1 cup uncooked quinoa\r\n\r\n1 red bell pepper, chopped\r\n\r\n1 orange bell pepper, chopped\r\n\r\n2 green onions, chopped\r\n\r\n1 medium cucumber, chopped and de-seeded\r\n\r\n1/8 cup olive oil\r\n\r\n2 tablespoons red wine vinegar (works without this ingredient, too)\r\n\r\n1 tablespoon balsamic vinegar\r\n\r\n1 tablespoon lemon juice\r\n\r\nSalt and pepper to taste\r\n\r\n1 avocado, sliced\r\n\r\nfrozen corn \r\n\r\ncherry tomatoes', 'In a medium sauce pot, bring the water and quinoa to a boil. Reduce the heat, cover, and let simmer for 15 minutes or until the quinoa has fully cooked.\r\nOnce the quinoa has finished cooking, pour into a large serving bowl, and stir in the bell pepper, green onion and cucumber.\r\nIn a small bowl, make the dressing by whisking together the olive oil, red wine vinegar, balsamic vinegar, lemon juice, salt and pepper. Taste as you go to make sure you achieve the flavor of your liking.\r\nPour the dressing over the quinoa and veggies. Stir to combine. Serve warm or cold with a few slices of avocado on top.\r\n', '', 'salad', 'Allison Douglas; http://tinyurl.com/o8cggqg', 'Vegan, Healthy, Cold, Potluck'),
(45, 'xqcwf0yh', 'Deviled Eggs', '', '', '', '12 deviled eggs', '', '6 hard boiled eggs (12 halves)\r\n1/4 cup mayonnaise\r\n1 tsp vinegar\r\n1 tsp mustard\r\nsalt\r\npepper\r\n', 'Half eggs lengthwise.\r\nRemove yolk and mash in bowl.\r\nAdd remaining ingredients to yolk.\r\nSpoon mixture back into egg halves.\r\nGarnish with paprika and parsley.\r\n', 'My platter holds 16 deviled eggs.', 'appetizer', 'Mom', 'Potluck, Cold'),
(46, 'SVXbJCQV', 'Taco Dip', '', '', '', '', '', '15.6 oz can of fat free refried beans (with jalapeno peppers if available)\r\n1 cup sour cream\r\n1/2 cup mayonnaise\r\n2 tbsp lemon juice\r\n1/4 tsp pepper\r\n2 tbsp taco seasoning mix\r\n8 ounces shredded colby or cheddar cheese\r\n4 chopped scallions\r\n3 diced plum tomatoes\r\n1 small can of sliced black olives\r\nBag of chips', 'On a large pizza pan, add the following:\r\n1st layer: refried beans\r\n2nd layer: sour cream, mayonnaise, lemon juice, pepper, taco seasoning mix\r\n3rd layer: cheese, scallions, tomatoes, olives\r\n\r\nBest if chilled.\r\n', '', 'appetizer', 'Mom', 'Cold, Potluck'),
(47, 'd9M6SftM', 'Fruit Dip', '', '', '2 hours 15 minutes', '', '', '7 oz jar of marshmallow creme\r\n8 oz cream cheese, softened\r\n1 tsp orange juice', 'Mix ingredients together with mixer. Chill for 2 hours. Serve with cut up fresh fruit. ', '', 'snack', 'Mom', ''),
(48, 'oBNDaXCE', 'Chop Chop Salad', '', '', '', '', '', 'Head of romaine lettuce\r\nScallion\r\n1 small can of black olives\r\n1 large tomato\r\nsliced almonds\r\n1 bell pepper\r\n', 'Chop up lettuce, scallions, tomato, and bell pepper into small pieces. \r\nAdd all ingredients together in salad bowl; mix well. ', 'Can also use roasted red peppers.', 'salad', 'Andrea', ''),
(49, 'VuV9nf32', 'Basic Muffins', '', '20-25 minutes', '', '10-12 muffins', '', '1.75 cups all-purpose flour\r\n1/4 cup sugar\r\n2 tsp baking powder\r\n1/2 tsp salt\r\n1 beaten egg\r\n3/4 cup milk\r\n1/3 cup cooking oil', 'Preheat oven to 400*\r\nIn a large mixing bowl stir together the flour, sugar, baking powder, and salt. \r\nMake a well in the center. \r\nCombine egg, milk, and oil. Add to the flour mixture.\r\nStir until just moistened; batter should be lumpy.\r\nGrease muffin cups or line with  paper bake cups; fill 2/3 full.\r\nBake for 20-25 minutes or until golden brown. \r\nRemove from pans; serve warm. ', 'For Blueberry muffins:\r\nPrepare basic muffins as above, except combine 3/4 cup fresh or thawed frozen blueberries, and 2 tablespoons additional sugar. Add 1 tsp finely shredded lemon peel if desired. Carefully fold into batter.  \r\n\r\nFor Cranberry muffins:\r\nCoarsely chop 1 cup fresh or frozen cranberries and combine with 1/4 cup additional sugar.\r\n\r\nFor Apple-Raisin Muffins:\r\nStir 1/2 tsp ground cinnamon into the flour mixture. Fold 1 cup chopped peeled apple and 1/4 cup raisins into batter. \r\n\r\nFor Jelly Muffins:\r\nSpoon 1 tsp jelly on top batter in each muffin cup before baking. \r\n\r\nFor Date-Nut Muffins:\r\nFold 2/3 cup coarsely chopped pitted dates and 1/3 cup chopped walnuts or pecans into batter.\r\n\r\nFor Banana Nut Muffins:\r\nDecrease milk to 1/2 cup. Stir 1 cup mashed banana and 1/2 cup chopped nuts into batter.\r\n\r\nFor Pumpkin Muffins:\r\nIncrease sugar to 1/3 cup. Add 1/2 cup canned pumpkin to egg mixture. Stir 1/2 tsp ground cinnamon and 1/2 tsp ground nutmeg into flour mixture. Stir 1/2 cup raisins into batter. ', 'breakfast', 'Mom, Betty Crocker recipe book?', ''),
(50, 'gQvgYPUs', 'Honey Wheat Muffins', '', '20 minutes', '', '12 muffins', '', '1 cup all-purpose flour\r\n1/2 cup whole wheat flour\r\n2 tsp baking powder\r\n1/2 tsp salt\r\n1 beaten egg\r\n1/2 cup milk\r\n1/2 cup honey \r\n1/4 cup cooking oil\r\n1/2 tsp finely shredded lemon peel', 'Preheat oven to 375*\r\nStir together both flours, baking powder, and salt.\r\nMake a well in the center.\r\nCombine egg, milk, honey, oil, and lemon peel; add to dry ingredients, stirring just until moistened (batter should be lumpy).\r\nGrease muffins cups or line with paper bake cups; fill 2/3 full.\r\nBake about 20 minutes.\r\n', 'For Sunflower Seed Muffins:\r\nPrepare as above except stir 1/2 cup shelled sunflower seeds into the flour mixture.', 'breakfast', 'Mom; Betty Crocker cook book?', 'Healthy');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cookbook`
--
ALTER TABLE `cookbook`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cookbook`
--
ALTER TABLE `cookbook`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=51;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
